version: '3.7'

services:
  mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: medtphp

  httpd:
    build: ./docker_files/httpd/
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/usr/local/apache2/htdocs/

  php:
    build: ./docker_files/php/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: medtphp